<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Priority Test"
           tests="5"
           failures="4"
           errors="0"
           skipped="0"
           time="0.047">
  <properties />
            <testcase name="fourthTest" time="0.016" classname="executeFailedTests.SampleTestClass2">
                <failure type="java.lang.ArithmeticException"
                  message="/ by zero"
              >
<![CDATA[java.lang.ArithmeticException: / by zero
  executeFailedTests.SampleTestClass2.fourthTest(SampleTestClass2.java:14)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
            <testcase name="fourthTest" time="0.015" classname="executeFailedTests.SampleTestClass2">
                <failure type="java.lang.ArithmeticException"
                  message="/ by zero"
              >
<![CDATA[java.lang.ArithmeticException: / by zero
  executeFailedTests.SampleTestClass2.fourthTest(SampleTestClass2.java:14)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
            <testcase name="fourthTest" time="0.000" classname="executeFailedTests.SampleTestClass2">
                <failure type="java.lang.ArithmeticException"
                  message="/ by zero"
              >
<![CDATA[java.lang.ArithmeticException: / by zero
  executeFailedTests.SampleTestClass2.fourthTest(SampleTestClass2.java:14)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
            <testcase name="fourthTest" time="0.000" classname="executeFailedTests.SampleTestClass2">
                <failure type="java.lang.ArithmeticException"
                  message="/ by zero"
              >
<![CDATA[java.lang.ArithmeticException: / by zero
  executeFailedTests.SampleTestClass2.fourthTest(SampleTestClass2.java:14)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.base/java.lang.Thread.run(Thread.java:844)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="thirdTest" time="0.016" classname="executeFailedTests.SampleTestClass2" />
      
</testsuite>
